export const LOGIN_USER = 'login_user';
export const LOGIN_FORM_IDLE = 'LOGIN_FORM_IDLE';

export const REGISTER_FORM_IDLE = 'REGISTER_FORM_IDLE';
export const CREATE_USER = 'CREATE_USER';

export const SAVE_USER = 'SAVE_USER';
export const DELETE_USER = 'DELETE_USER';

export const FETCH_PRISONERS = 'FETCH_PRISONERS';
export const FETCH_PRISONERS_SUCCESS = 'FETCH_PRISONERS_SUCCESS';
export const FETCH_PRISONERS_FAILED = 'FETCH_PRISONERS_FAILED';

export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULES_FAILED = 'FETCH_SCHEDULES_FAILED';

export const FETCH_VISIT = 'FETCH_VISIT';
export const FETCH_VISIT_SUCCESS = 'FETCH_VISIT_SUCCESS';
export const FETCH_VISIT_FAILED = 'FETCH_VISIT_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const UPDATE_PROFILE_FORM_IDLE = 'UPDATE_PROFILE_FORM_IDLE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';
export const UPDATE_PASSWORD_FORM_IDLE = 'UPDATE_PASSWORD_FORM_IDLE';

export const VISIT_PRISONER = 'VISIT_PRISONER';
export const VISIT_FORM_IDLE = 'VISIT_FORM_IDLE';